### ISSUE TITLE
Caffe error

### ISSUE THREAD

**Issue by vijayg78** [aharley/segaware#1]
Hi,
I built the caffe from this repo and i am getting an error that 
Error parsing text-format caffe.NetParameter: 62:15: Message type "caffe.LayerParameter" has no field named "deletebottom".

What might be the issue?
Regards, Vijay

**Comment by aharley** [comment]
Thank you for bringing this to my attention! I updated the repo. This error should be gone now.

**Comment by vijayg78** [comment]
That error has gone now. One additional question.
Do you need the matlab dependency for building caffe? I did build caffe without matlab but I see in repo that the output of test_res.sh is .mat files which is used for predictions.

Is it possible to run the evaluation without matlab dependency?

**Comment by aharley** [comment]
You would have to write a bit of new code, but it's certainly possible. I just use the Matwrite layer to output the softmax predictions. Also the VOC evaluation code is written in Matlab (mostly by the DeepLab people). You can replace those parts with whatever you like, and it will not affect the main network.
