### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by zhwis** [aharley/segaware#3]
I am currently running ./test_res.sh on a  11GB of GPU memory,gtx1080ti. But when I run the script, it immediately throws out an error:
I0911 12:46:39.811416 18216 caffe.cpp:252] Running for 1449 iterations.
F0911 12:46:40.284883 18216 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
and since you are already at batch size = 1 ,I don't know how much real memory ,  or What should I do?

**Comment by aharley** [comment]
What is your image size? At 513x513 or less, it should fit in memory.

**Comment by zhwis** [comment]
I used voc_val.txt of VOC2012,and the maximum side is < 513,To solve this problem，I change the crop_size value in test_res.sh and segaware/config/res/test.prototxt is <=257. and  I tried to resize the image smaller，but the effect is relatively poor. The problem should not be here，but I do not know how to do it

**Comment by StOnEGiggity** [comment]
Hi, there is the same error like @zhihuiwisdom , it looks like no detail about the environment and what type of GPU is.is It possible to share with us?Thanks a lot.

**Comment by aharley** [comment]
Thanks for the comments and reminders!
I was using cuda-8.0, a Quadro M6000 24GB GPU, and Nvidia driver version 375.26.
After the CVPR deadline (1 week) I can try to release a more memory-efficient version. 
I think the VGG16 version works with a 12GB gpu and no memory tricks.
